---
- name: Deploy AS3
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - ../creds/big_creds.yaml

  vars:
    uri_method: POST

  tasks:

  - name: Create VS
    uri:
      url: https://35.176.82.189/mgmt/shared/appsvcs/declare/
      user: "{{ bigip_user }}"
      password: "{{ bigip_pass }}"
      method: "{{ uri_method }}"  
      body: "{{ lookup('file','as3_dec.json') }}"
      force_basic_auth: yes
      status_code: 200
      validate_certs: no
      body_format: json




...